version: "3.8"

services:
  openproject:
    image: openproject/community:13.4.1
    ports:
      - "30080:80"
    volumes:
      - ./db-data:/var/lib/postgresql/data
      - ./data:/var/openproject/assets
    environment:
      SECRET_KEY_BASE: ${SECRET_KEY_BASE}
