version: "3.8"

services:
  openproject:
    image: openproject-custom:13.4.1
    ports:
      - "${HOST_PORT}:80"
    volumes:
      - ./db-data:/var/lib/postgresql/data
      - ./data:/var/openproject/assets
    environment:
      SECRET_KEY_BASE: ${SECRET_KEY_BASE}
      OPENPROJECT_HOST__NAME: ${HOST_ADDRESS}:${HOST_PORT}
      OPENPROJECT_HTTPS: "false"
      OPENPROJECT_DEFAULT__LANGUAGE: ja
